name: Tests CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn test


